apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: analytics-svc-9296
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/analytics-svc-9296
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
